### PR TITLE
Add sensor 114

### PR DESCRIPTION
**Pull request by Inkering**
Added the new sensor. Already swapped the api key to the new one under Scott's account.

### CODE REVIEW

**Review by anushadatar — APPROVED** [review]
Thanks for taking this on and also swapping the API key. LGTM but I also didn't pull or test this given it's a copy of the pattern; if you'd like me to do something more thorough just let me know.

**Comment by anushadatar** [comment]
Is this the only sensor in Revere? Might be nice to add them all in the same commit for making it easier to search through later.

**Comment by Inkering** [comment]
Yeah I think this is fine. we'll have to test more thoroughly once added to the front end client. This is the only "new one" that is live at the moment which we know how to ingest. The other new sensors have a different set of pollutants // a different api response we need to handle.

**Comment by Inkering** [comment]
SN000-46 is also now in revere, waiting on Scott for approx. coordinates

**Pull request merged**
